version: '3.8'

services:
  app:
    image: mariussarca/idea-generator:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://db:1433;databaseName=api_data;encrypt=false
      - SPRING_DATASOURCE_USERNAME=ideas
      - SPRING_DATASOURCE_PASSWORD=ideas
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  mssql-data: